### ISSUE TITLE
Korean backspace expected behaviour

### ISSUE THREAD

**Issue by GreyWyvern** [GreyWyvern/virtual-keyboard#10]
I've been playing around with the Korean keyboard algorithm code and studying up on it online, @VitaJane.

Can you tell me what the expected behaviour would be for typing in the following Korean character sequence on an actual keyboard?

1. ㅈ
2. ㅜ
3. ㅅ
4. ㅔ
5. Bksp
6. Bksp
7. ㅅ

I kind of expect the algorithm to add the ㅅ character to the bottom of the previous Hangul, but since the last character it backspaced was the last of the current Hangul/Jamo, it starts a new Hangul instead.

Even if that seems wrong to me, I would like it to match the way actual Korean keyboards work.

**Comment by GreyWyvern** [comment]
I've created a potential v1.54 release branch here if you'd like to test it, @VitaJane. It includes my *expected* behaviour for the Korean Input Algorithm above. It also compactifies almost all the Korean Input code into a single block that can be entirely removed without causing errors with the rest of the script.

It **also** includes a new selector feature, where if you click the title twice, it will change the list to the English version of the names and sort the list based on that.

https://github.com/GreyWyvern/virtual-keyboard/tree/v1-54

Please test this and let me know what you think.

**Comment by VitaJane** [comment]
Hello! Sorry, just saw this. The functionality I originally had is how a Korean Keyboard typically works. Unfortunately I'm pretty busy today, but I can take a look at the changes tomorrow, if I can't make time today.

**Comment by VitaJane** [comment]
Took a look at it and it looks good to me! I did make a PR with more typical Korean Keyboard functionality in case you'd rather use that.
